Repository porter-dev/porter, pull requests merged in 2021-06, with the labels that each got.

#791 [0.5.0] [Bugfix] - Fix chart list update on change of current view
  dashboard/src/main/home/cluster-dashboard/chart/ChartList.tsx
Labels: bug, frontend

#776 [0.5.0] [Frontend, API] Launchflow Improvements
  dashboard/src/components/Button.tsx
  dashboard/src/components/repo-selector/ActionConfEditor.tsx
  dashboard/src/components/repo-selector/ContentsList.tsx
  dashboard/src/components/repo-selector/RepoList.tsx
  dashboard/src/components/values-form/FormDebugger.tsx
  dashboard/src/components/values-form/InputRow.tsx
  dashboard/src/components/values-form/ValuesForm.tsx
  dashboard/src/main/home/cluster-dashboard/ClusterDashboard.tsx
  dashboard/src/main/home/cluster-dashboard/dashboard/Dashboard.tsx
  dashboard/src/main/home/cluster-dashboard/dashboard/NamespaceList.tsx
  dashboard/src/shared/Context.tsx
  dashboard/src/shared/api.tsx
  dashboard/src/shared/types.tsx
  server/api/git_repo_handler.go
  server/router/router.go
Labels: frontend, server

#831 [0.5.0] [bugfix] Update chart uses old chart config instead of new one
  dashboard/src/main/home/cluster-dashboard/expanded-chart/ExpandedChart.tsx
Labels: bug
