Repository porter-dev/porter, pull requests merged in 2022-12, with the labels that each got.

#2583 [hotfix] Fix link to docs in the Help navbar
  dashboard/src/main/home/navbar/Help.tsx
Labels: bug, frontend

#2581 [POR-824] Case for Istio ingress if present
  api/server/handlers/namespace/get_ingress.go
  dashboard/src/main/home/cluster-dashboard/expanded-chart/ExpandedChart.tsx
  go.mod
  go.sum
  internal/kubernetes/agent.go
Labels: enhancement, frontend, server

#2564 [POR-809] feat: support opening app details in new tab
  dashboard/src/main/home/cluster-dashboard/chart/Chart.tsx
Labels: enhancement, frontend
